# Generated by Django 2.0 on 2018-05-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=40)),
                ('sigla', models.CharField(db_column='Sigla', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('data', models.DateField(db_column='Data')),
                ('status', models.CharField(db_column='Status', max_length=10)),
                ('planodeensino', models.CharField(db_column='PlanoDeEnsino', max_length=1000)),
                ('cargahoraria', models.IntegerField(db_column='CargaHoraria')),
                ('competencias', models.CharField(db_column='Competencias', max_length=100)),
                ('habilidades', models.CharField(db_column='Habilidades', max_length=100)),
                ('ementa', models.CharField(db_column='Ementa', max_length=1000)),
                ('conteudopogramatico', models.CharField(db_column='ConteudoPogramatico', max_length=1000)),
                ('bibliografiabasica', models.CharField(db_column='BibliografiaBasica', max_length=1000)),
                ('bibliografiacomplementar', models.CharField(db_column='BibliografiaComplementar', max_length=1000)),
                ('percentualpratico', models.IntegerField(db_column='PercentualPratico')),
                ('percentualteorico', models.IntegerField(db_column='PercentualTeorico')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtinicniomatricula', models.DateField(db_column='DtInicnioMatricula')),
                ('dtfimmatricula', models.DateField(db_column='DtFimMatricula')),
                ('ano', models.IntegerField(db_column='Ano')),
                ('semestre', models.IntegerField(db_column='Semestre')),
                ('turma', models.CharField(db_column='Turma', max_length=5)),
                ('metodologia', models.CharField(db_column='Metodologia', max_length=1000)),
                ('recursos', models.CharField(db_column='Recursos', max_length=1000)),
                ('criterioavaliacao', models.CharField(db_column='CriterioAvaliacao', max_length=1000)),
                ('planodeaulas', models.CharField(db_column='PlanoDeAulas', max_length=1000)),
                ('idcoordenador', models.ForeignKey(db_column='IdCoordenador_id', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Coordenador')),
                ('idcurso', models.ForeignKey(db_column='IdCurso_id', on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Curso')),
                ('iddisciplina', models.ForeignKey(db_column='IdDisciplina_id', on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Disciplina')),
                ('idprofessor', models.ForeignKey(db_column='IdProfessor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Professores')),
            ],
        ),
    ]
