# Generated by Django 2.0 on 2018-05-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_column='Login', max_length=1000)),
                ('senha', models.CharField(db_column='Senha', max_length=10)),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=1000)),
                ('celular', models.CharField(db_column='Celular', max_length=15)),
                ('dtexpiracao', models.DateField(db_column='DtExpiracao')),
                ('ra', models.IntegerField(db_column='RA')),
                ('foto', models.CharField(db_column='Foto', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_column='Login', max_length=1000)),
                ('senha', models.CharField(db_column='Senha', max_length=10)),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=1000)),
                ('celular', models.CharField(db_column='Celular', max_length=15)),
                ('dtexpiracao', models.DateField(db_column='DtExpiracao')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(db_column='Assunto', max_length=1000)),
                ('referencia', models.CharField(db_column='Referencia', max_length=1000)),
                ('conteudo', models.CharField(db_column='Conteudo', max_length=100)),
                ('status', models.CharField(db_column='Status', max_length=10)),
                ('dtenvio', models.DateField(db_column='DtEnvio')),
                ('dtresposta', models.DateField(db_column='DtResposta')),
                ('resposta', models.CharField(db_column='Resposta', max_length=1000)),
                ('idaluno', models.ForeignKey(db_column='IdAluno_id', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_column='Login', max_length=1000)),
                ('senha', models.CharField(db_column='Senha', max_length=10)),
                ('nome', models.CharField(db_column='Nome', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=1000)),
                ('celular', models.CharField(db_column='Celular', max_length=15)),
                ('dtexpiracao', models.DateField(db_column='DtExpiracao')),
                ('apelido', models.CharField(db_column='Apelido', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='idprofessores',
            field=models.ForeignKey(db_column='IdProfessores_id', on_delete=django.db.models.deletion.DO_NOTHING, to='contas.Professores'),
        ),
    ]
